### ISSUE TITLE
Unsoundness caused by different `GhostEnum` layout

### ISSUE THREAD

**Issue by chipshort** [yasuo-ozu/addr_of_enum#1]
Unfortunately this crate currently relies on the assumption that an enum containing fields of type `T` has the same layout as an enum containing `MaybeUninit<T>`. However, this is not always the case. It is mentioned in the [rust docs](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html#layout-1) of `MaybeUninit` that
> types containing a field of type `T` may be laid out (and sized) differently than if that field were `MaybeUninit<T>`

Here is a test that fails for that reason:
```rust
#[derive(AddrOfEnum, PartialEq, Eq)]
enum MyOption<T> {
    None,
    Some(T),
}

#[test]
fn test_option() {
    let some = MyOption::Some(false);

    match &some {
        MyOption::Some(item) => {
            assert_eq!(item as *const bool, addr_of_enum!(&some, Some, 0)); // <- this will fail (off by one)
        }
        _ => panic!(),
    }
}
```

In this specific example, the compiler does niche optimization because it knows that only `0` and `1` are valid values for `bool`, so it can use one of the remaining values as `None`. However, `MaybeUninit<bool>` could, by definition, have any bit pattern, so the same optimization is not possible there.

**Comment by chipshort** [comment]
@yasuo-ozu friendly ping

**Comment by yasuo-ozu** [comment]
@chipshort Sorry for late reply. I was missing of the fact.

I should be deal with niche optimizing and item shuffling. (Maybe forcing `#[repr(C)]`?)
Thanks for your report.

**Comment by chipshort** [comment]
Thanks for the reply.
Yes, I believe forcing `#[repr(C)]` should fix it.

**Comment by yasuo-ozu** [comment]
Fix released. Thank you!
